### ISSUE TITLE
希望增加支持【Coze 智能体】和【腾讯元器】，支持其他LLM参数

### ISSUE THREAD

**Issue by hhun** [AnimeAIChat/xiaozhi-server-go#30]
## 有些供应商的接口不是  `chat/completions` 结尾
1. 【腾讯元器】接口网址 `https://yuanqi.tencent.com/openapi/v1/agent/chat/completions`
2. 【Coze智能体】接口网址 `https://api.coze.cn/v3/chat`
3.  【智谱智能体】接口网址 `https://open.bigmodel.cn/api/llm-application/open/v3/application/invoke`

地址规则问题不大，例如：Coze可以通过网址后面增加 `?` 或者 `#` 也能访问。
示例： `https://api.coze.cn/v3/chat?chat/completions`

---

但是自定义参数兼容性就非常有必要
## 建议增加其他LLM参数：
1. 【腾讯元器】没有 `model` 参数，有 `assistant_id` 和 `user_id` 参数。
2. 【Coze智能体】没有 `model` 参数，有 `bot_id` 和 `user_id` 参数。
3. 【智谱智能体】没有 `model` 参数，有 `app_id` 参数。
4. 【百川智能】的知识库是要增加
```
"knowledge_base": {
    "ids": ["kb-xxxxxxx"]
}
```

---

OpenAi 消息格式 `{ role: "user", content: "提问" }`
腾讯元器 消息格式 `{ role: "user", content: { "type":"text", "text":"提问" } }`

**Comment by hhun** [comment]
看到 `src/configs/config.go` 里面有 `extra`，`config.yaml` 里面 的 `bot_id` 是这样设置吗？

```
# LLM配置
LLM:
    ChatGLMLLM:
      # 定义LLM API类型
      type: openai
      model_name: ""
      url: "https://api.coze.cn/v3/chat?"
      api_key: sk-xxxxxx
      # 额外参数
      extra:
        bot_id: "123456"
        user_id: "0"
```
我这样设置使用Coze还是没有用，好extra没有生效
