### ISSUE TITLE
希望支持LLM 额外参数 Extra

### ISSUE THREAD

**Issue by hhun** [AnimeAIChat/xiaozhi-server-go#38]
看到 `src/configs/config.go` 里面有 `extra`，`config.yaml` 里面 的 `bot_id` 是这样设置吗？

```
# LLM配置
LLM:
    ChatGLMLLM:
      # 定义LLM API类型
      type: openai
      model_name: ""
      url: "https://api.coze.cn/v3/chat?"
      api_key: sk-xxxxxx
      # 额外参数
      extra_test: "123456"
      extra:
        bot_id: "123456"
        user_id: "0"
```
我这样设置，`bot_id` 和 `user_id` 两个参数没有生效，没有传递过去。
